### ISSUE TITLE
Need to change how ENMeval is installed

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#19]
If the only way to get the shiny app to work is to use the edits version of ENMeval, we'll have to change how this gets installed by default.

**Comment by bobmuscarella** [comment]
This command should load Jamie's new version of ENMeval:  
 > install_github("bobmuscarella/ENMeval@edits")

**Comment by mlammens** [comment]
Right @bobmuscarella. So should we make `devtools` a required package too then?

**Comment by bobmuscarella** [comment]
I guess so.  There is something that seems strange to me about this,
though, because (as far as I understand) it saves the new (test) version to
the users library without them necessarily knowing about it.   Surely there
is at least some etiquette issue here?  Especially since the
"updateProgress" argument in the new ENMevaluate function is not mentioned
in the current documentation, etc.  Probably not a big deal for now and we
can just add this to the next official release of ENMeval...  thoughts?

**Comment by mlammens** [comment]
I agree, but also think that for now, we are not *really* intending for this app to be downloaded by users, but to be hosted on shinyapps.io. We could make a warning to those how download this about what the consequences are though.

**Comment by ndimhypervol** [comment]
Yes, I was envisioning that this change, and a couple of older and future ones, could be rolled out into a new version of ENMeval at some point. But for now, as we don't plan on distributing this widely, I agree with Matt that it should be okay.
