### ISSUE TITLE
Errors with partitioning methods in ENMeval - probably needs error control

### ISSUE THREAD

**Issue by bobmuscarella** [ndimhypervol/wallace#20]
Although the block and checkerboard (1 and 2) methods worked fine for all species I've tried, i get errors if I select either the jackknife or random k fold methods.

For kfold it was:
Error in if (k == 1) { : missing value where TRUE/FALSE needed

For jackknife it was:
Error in evaluate(test.val, bg, mod) : 
  cannot evaluate a model without absence and presence data that are not NA

For the short term, we may just eliminate these as options...

**Comment by bobmuscarella** [comment]
I think the kfolds doesn't work because it requires specifying how many kfolds in the ENMevaluate function but this is null in the shiny implementation.  I'm not sure the problem with the jackknife option...

**Comment by ndimhypervol** [comment]
I removed functionality for randomkfold, and am puzzled by jackknife's error. Looking into it.

**Comment by ndimhypervol** [comment]
Fixed the problems with jackknife -- it was due to NAs in extract(). This was likely a problem because we were inputting small extents that got env cells cut off for locs on the border of the backg extent when the crop and mask were done. I added one cell length on to both bb and mcp, and the problem is fixed.
