### ISSUE TITLE
Additional user inputs and downloads

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#33]
From @ndimhypervol - Lots of user inputs need to be coded. I think we want to make as much downloadable as possible?

**Comment by ndimhypervol** [comment]
User inputs I envision:
- csv of occs that can be merged with GBIF data, or not
- rasters? there might be a file size limit we will need to impose
- custom background polygon
- user-defined groups for ENMeval

Any more?

**Comment by ndimhypervol** [comment]
Just added user-selected polygon for background.

**Comment by ndimhypervol** [comment]
CSV of occs was also implemented.

**Comment by ndimhypervol** [comment]
You can now use the user-defined kfold, as long as you have one column in your input csv for the occ groups and one for the backg groups. Once you select "user" for method, you select which column in your csv is for which group. I tested it and it seems to work, but this needs more testing. It complicates the code a little more because we need to keep track of these new fields, and thus the input CSV as a separate entity from df and gbifoccs. Perhaps we can simplify this somewhere down the road.

**Comment by ndimhypervol** [comment]
Closing this because I think I implemented all of these inputs.
