### ISSUE TITLE
Going forward -- need updates!

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#45]
Hello all. Less of an "issue" than a check-in. I wanted to see where everything is so we can plan the rest of our dev time efficiently. We have approx. 1.5 weeks from now, and I'd like dev to be done by next Sunday so we can concentrate on the video the week of the 30th. Can everyone update us on the progress of everything below? Thanks.

@bobmuscarella 
- separating data partitioning from ENMevaluate() call (I think that's how you were going to do it)
- integrate Bioclim algorithm and have it partitioned
- I just thought of this, but we'll need to output the same graphs, prediction rasters, results table for Bioclim too, won't we? thus, wouldn't it make the most sense to just put it into ENMeval? what are your thoughts, Bob?

@mlammens 
- you can't start this until Bob sends you something, but Shiny-ify the above
- can we make a new URL at UConn on the same server for WALLACE 2.0? the volume will be low b/c it will just be judges accessing for now, and we know it works, thus it's the safest bet

@BrunoVilela 
- I've already put some requests into the other "some issues I found" issue
- generation of Markdown doc that details the user run and can be run as R code to reproduce analysis (this seems to me like the most work, but can you prove me wrong? I am more than willing to help out with this, but you'll need to educate me on how it works)

me
- I'd personally like to also integrate GLM into the mix, but it would be easiest to just "drop" it in after Bioclim is added (does anyone have a good idea of concrete steps to build robust GLMs in the SDM framework? we'll have to remove collinearity of predictors via vifstep() or some such iterative stepwise function. anything else that makes it different from Maxent?)
- working on restructuring ui.R to make it match Rob's grand vision for the user interface

Thanks all. Almost done!

**Comment by bobmuscarella** [comment]
I sent a first stab of my stuff to Matt a few days ago so he may have more to comment on as far as integration into Shiny...  BUT

* [Here is a link to code I wrote to (including some testing): ](https://github.com/bobmuscarella/Partitioning_and_Bioclim_in_ENMeval/blob/master/Partition_and_Bioclim.R)
 * Separate data partitioning from ENMevaluate() call 
 * Integrate Bioclim algorithm

***Output***: I think we can just provide the results table and prediction raster (there is only 1 since there are no alternative settings for BioClim).  I'm not sure what kind of graph (comparable to RM and feature classes line plots in ENMeval) would make sense... *Any other ideas?*

***Question***: BioClim does not require background points.  However, they are needed to get some evaluation stats (e.g., AUC, AUCdiff).  So, as it's currently written, background points are generated up front (regardless of Maxent or BioClim choice) and then similar results tables are generated.  *Does this seem like a good idea to folks?*

***GLM***: I'm a bit hesitant to include GLM because I am skeptical of the automated variable selection stuff in the GLM framework. (Yes, I realize the Maxent does automated variable selection but it is different).  I guess you would select variables on the full model and then run the partitioned dataset using those variables?  Also, it is my understanding that GLMs are really working with a presence / pseudo-absence framework rather than a presence/background framework.  This distinction makes it kind of odd to use randomly selected 'background' points as pseudo-absence.  In any case, we could add it to show that Wallace is flexible.  I think people generally report [the squared adjusted deviance](https://modtools.wordpress.com/2013/08/14/dsquared/) when using GLMs for SDM.  




Here is some code that may be useful for evaluation stats:

    library(SDMTools)

    # The following function calculates evaluation stats for GLMs
    # 'pa' is a vector of 1's and 0's used for logistic regression.
    # 'mod' is the lm model object.
    # You can choose the threshold...

    eval.stats <- function(pa, mod, thresh=0.5){
	deviance <- 1 - (deviance(mod) / mod[['null.deviance']])
	conmat <- confusion.matrix(pa, fitted(mod), thresh)
	kappa <- Kappa(conmat)
	omission <- omission(conmat)
	sensitivity <- sensitivity(conmat)
	specificity <- specificity(conmat)
	prop.correct <- prop.correct(conmat)
	TPP <- conmat[4] / (conmat[4]+conmat[3])
	TSS <- sensitivity + specificity - 1
	res <- t(data.frame(deviance, kappa, omission, sensitivity, specificity, prop.correct, TPP, TSS))
	colnames(res) <- "Value"
	return(res)
	}

**Comment by robertpanderson** [comment]
Bob: I’m ccing you, in case the reply to all doesn’t work … I’m still not using the Github messaging.

Bob et al.:

Great progress.

Regarding output: people can “tune” BIOCLIM by varying the number of variables (to be selected randomly) and by changing how much of the tails to cut off.  DIVA-GIS lets you do this, but I don’t know about dismo.  I highly suggest not implementing anything along these lines that dismo doesn’t do already.

Regarding background: Remember that (I think) the background points used for evaluation should come from the same spatial regions as the positive occurrence records used for evaluation … correct?  (except in cases where we take background points across the full study region, to be able to compare AUCs among different masked spatial partitions).

Regarding GLMs: I say forget about a third technique. And if we wanted to do a third technique, I’d highly suggest GAMs instead. But let’s just make Wallace good at Maxent and ok at BIOCLIM, and feasible/attractive for expansion.  So that somebody else who understands GAMs well will want to implement them in the near future. Btw, regarding background  vs. pseudoabsence cells, I hope that the footnote on p. 14 of my 2013 ANYAS paper is helpful.

Best to all …
Rob

*************************************
Robert P. Anderson, Ph.D.
Professor, Department of Biology
526 Marshak Science Building
City College of New York, City Univ. of New York
160 Convent Avenue
New York, NY 10031, USA

Telephone: (212) 650-8504
http://web.sci.ccny.cuny.edu/~anderson/
NOTE NEW E-MAIL: randerson@ccny.cuny.edu<mailto:randerson@ccny.cuny.edu>

**Comment by ndimhypervol** [comment]
This is a running list of stuff that Rob and I talked about in no specific order. I'm going to try to tackle these, but if someone wants to help out, let me know please.

- detailed text for abbrev of tab name at top on left bar
- change tab text to "visualize prediction"
- change raster save names for mtp and p10
- allow download background polygon shapefile, possibly allow download of clipped rasters (if no download, provide non-functional button to show capability)
- make clear in first tab for user entry of CSV what must columns be
- offer multiple raster file formats for download for prediction and clipped grids (gtiff, ascii, grd)
- and offer .jpg or .png for prediction
- ditch user-specifed env data, maybe also user-specified partitioning b/c it's a little confusing (user currently inputs a csv with partitioning column in tab 1, but partitioning is done later in tab 5)

**Comment by mlammens** [comment]
I just started working with the files that @bobmuscarella sent last week. I'll let you all know how that goes soon.
